# Generated by Django 3.2.22 on 2024-01-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
